title: "Anirudh's Blog"
name: "Anirudh's Blog"
baseurl: "/blogs"
url: "https://anirudhxplorer.github.io/"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

feed:
  path: feed.xml

markdown: kramdown
paginate: 10
paginate_path: "/page:num/"